### ISSUE TITLE
`Tabs` class/folder structure does not follow psr-4 autoloading conventions.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/publisher-media-kit#118]
### Describe the bug

The `composer.json` file for this plugin sets up psr-4 autoloads for classes within the `PublisherMediaKit` namespace.

However, the only class `PublisherMediaKit\Blocks\BlockContext\Tabs` is in the file `includes/classes/blocks/BlockContext/Tabs.php` so does not meet this convention. The difference is that the namespace fragment `Blocks` uses an uppercase B, while the folder name `blocks` uses a lowecase B.

This hasn't come to light as an issue previously as the file for the class is manually required within the main plugin file, the composer autoloader isn't included in the distributed version on WordPress.org so this hasn't caused a problem. I expect the file is manually required as the autoloader was failing on case sensitive file systems.

https://github.com/10up/publisher-media-kit/blob/e2cb88b3fca861b884ec58244e48301e0908f409/publisher-media-kit.php#L37

I see two possible fixes
* Remove PSR-4 autoloading
* Rename the namespace to match the lowercase B of the folder name. I'm suggesting renaming the namespace (even though it's not great to have a mix of case) as PHP namespaces are case insensitive but not all file systems are.

### Steps to Reproduce

1. Clone the repository
2. Install composer with the optimized autoloader switch `composer install --no-dev --optimize-autoloader`
3. Composer will warn: `Class PublisherMediaKit\Blocks\BlockContext\Tabs located in ./includes/classes/blocks/BlockContext/Tabs.php does not comply with psr-4 autoloading standard. Skipping.`

### Screenshots, screen recording, code snippet

```
$> composer install --no-dev --optimize-autoloader
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Class PublisherMediaKit\Blocks\BlockContext\Tabs located in ./includes/classes/blocks/BlockContext/Tabs.php does not comply with psr-4 autoloading standard. Skipping.
```

### Environment information

- OS: macOS Monterey 12.6.1
- PHP: 7.4.30

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@peterwilsoncc I agree with this,

> Rename the namespace to match the lowercase B of the folder name. I'm suggesting renaming the namespace (even though it's not great to have a mix of case) as PHP namespaces are case insensitive but not all file systems are.

But what if we change the folder name from `blocks` to `Blocks` (_does not seem a good practice though_)?

**Comment by peterwilsoncc** [comment]
@faisal-alvi My minor concern with changing the folder name is that it could cause problems if another plugin is requiring the file on a case sensitive file system. It seems really unlikely though.

In WP 6.0 or 6.1, the upgrade to [WordPress/Requests](https://github.com/WordPress/Requests/) was reverted due to an issue within the Core updater when changing the case of folders and file names so, if we decide it's worth the risk of changing the folder name, we'd need to make sure the Plugin Updater doesn't suffer the same issue.

**Comment by faisal-alvi** [comment]
@peterwilsoncc agree! I'd say, let's proceed with renaming the namespace.
