### ISSUE TITLE
Update is not working

### ISSUE THREAD

**Issue by kelvinballoo** [10up/publisher-media-kit#136]
### Describe the bug

When I try to change a value and press 'Update', I get the error 'Updating failed. The response is not a valid JSON response.'

### Steps to Reproduce

1. Go to the Media page
2. Update a value, e.g. Change the 'The average female visitor is 38 years old' to 'The average female visitor is 37 years old'
3. Click Update

### Screenshots, screen recording, code snippet

<img width="1425" alt="Screenshot 2023-03-24 at 3 15 44 PM" src="https://user-images.githubusercontent.com/125576926/227508940-44687626-e22b-4cbf-9fb4-2b5468ca4283.png">

### Environment information

Device MacBook Pro (Retina, 15-inch, Mid 2015)
OS Mc Os Monterey 12.6.3
Chrome Version 111.0.5563.110 (Official Build) (x86_64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kelvinballoo** [comment]
Even Publishing the page throws an error.

**Comment by chandrapatel** [comment]
I have tried to reproduce this issue in different WordPress versions including 6.4.1, 6.3.2, 6.2.2, 6.1.1 but I'm able to save as draft and able to publish it. I'm using PHP 8.2.10 version, 2021 theme (and also tried couple of Newspack themes) and no other plugins installed.
