### ISSUE TITLE
Enhancing the visuals

### ISSUE THREAD

**Issue by kelvinballoo** [10up/publisher-media-kit#137]
### Is your enhancement related to a problem? Please describe.

There is no problem but the page would look much better with some padding in those highlighted areas.
So
<img width="1188" alt="Screenshot 2023-03-24 at 3 26 04 PM" src="https://user-images.githubusercontent.com/125576926/227510183-8d0b81e2-1d91-4831-bacc-e9eee81a4064.png">
me are too close to the container borders

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chandrapatel** [comment]
I have checked spacing issue in default 2021 theme and couple of Newspack themes and it does have spacing, so it seems like this is related to specific theme(s). If theme has enabled spacing controls then it can be added from block editor.
