### ISSUE TITLE
Functionality of the Publisher Media Kit

### ISSUE THREAD

**Issue by kelvinballoo** [10up/publisher-media-kit#138]
### Describe your question

So, the plugin will create a 'Media Kit' page.
What happens if I rename that filed to let's say 'Kelvin's Kit'.
If I deactivate and activate back the plugin, is the plugin supposed to create a new 'Media Kit' page?
Currently it won't unless I delete the page itself.
I was just curious as to how the plugin identifies there has already been a 'Media Kit' page created and renamed?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@kelvinballoo thanks for asking the question. The plugin checks for the page slug `media-kit` so even if you change the page name, it won't create a new page unless the page slug is changed or the page is moved to trash.

**Comment by faisal-alvi** [comment]
Closing the ticket, please re-open if required.

**Comment by jeffpaul** [comment]
@faisal-alvi perhaps that's worth adding as an FAQ in the readme?
