### ISSUE TITLE
Unable to update the cover image

### ISSUE THREAD

**Issue by kelvinballoo** [10up/publisher-media-kit#139]
### Describe the bug

It seems like there is no option to update the Media Kit cover image
I assume editors should be able to change this according to what they want

<img width="1440" alt="Screenshot 2023-03-24 at 4 07 44 PM" src="https://user-images.githubusercontent.com/125576926/227517278-2b2895de-9596-4e66-8688-5117b1581068.png">

### Steps to Reproduce

1. Go to Media Kit Page
2. Click on the Cover Image
3. There is a 'Clear Media' button but there is no way to update to add a new one.

### Screenshots, screen recording, code snippet

<img width="272" alt="Screenshot 2023-03-24 at 4 06 42 PM" src="https://user-images.githubusercontent.com/125576926/227517692-0693c8dc-bab7-4ee5-bf66-7ecdd52b73f9.png">

### Environment information

Device MacBook Pro (Retina, 15-inch, Mid 2015)
OS Mc Os Monterey 12.6.3
Chrome Version 111.0.5563.110 (Official Build) (x86_64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sidsector9** [comment]
Hi @kelvinballoo, you can replace the Cover image by using the Replace button as show in the image below:

<img width="765" alt="Screenshot 2023-10-19 at 11 50 12 AM" src="https://github.com/10up/publisher-media-kit/assets/17757960/a8d91fe6-b3fd-4463-8a9b-33c098604192">

Closing this issue as resolved.
