### ISSUE TITLE
Unable to update the male/female icon

### ISSUE THREAD

**Issue by kelvinballoo** [10up/publisher-media-kit#140]
### Describe the bug

Whenever, I try to replace the male icon with another of my own picture, it doesn't get uploaded.
It's specifically using the upload option as per the image attached.

<img width="672" alt="Screenshot 2023-03-24 at 4 25 43 PM" src="https://user-images.githubusercontent.com/125576926/227521148-17b5634d-3c28-4f24-9453-47b41bce0d8a.png">

### Steps to Reproduce

1. Go to a Media Kit page
2. Click on the male icon
3. Click on Replace and Upload
4. Browse for a file to be uploaded

### Screenshots, screen recording, code snippet

The file doesn't get uploaded
<img width="490" alt="Screenshot 2023-03-24 at 4 25 57 PM" src="https://user-images.githubusercontent.com/125576926/227521921-b4f7fbc0-5daa-4bc2-a987-2fe575de7ed8.png">

### Environment information

Device MacBook Pro (Retina, 15-inch, Mid 2015)
OS Mc Os Monterey 12.6.3
Chrome Version 111.0.5563.110 (Official Build) (x86_64)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by punndcoder28** [comment]
Hi. I can take this up. Dig deeper and work on a fix.

**Comment by chandrapatel** [comment]
I have tried to reproduce this issue in different WordPress versions including 6.4.1, 6.3.2, 6.2.2, 6.1.1 but I'm able to save as draft and able to publish it. I'm using PHP 8.2.10 version, 2021 theme (and also tried couple of Newspack themes) and no other plugins installed.
