### ISSUE TITLE
Update browserlist DB for caniuse-lite

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/publisher-media-kit#149]
### Describe the bug

During an `npm install` an alert is shown that the caniuse browserlist database is out of date. It can be updated by running `npx browserslist@latest --update-db`.

This will help reduce redundant JS and CSS required to support unsupported browsers.

### Steps to Reproduce

1. Clone the repository
2. Run `npm i; npm run build`
3. During this process a warning will be shown:
   ```
   Browserslist: caniuse-lite is outdated. Please run:
   npx browserslist@latest --update-db
   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
   ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by punndcoder28** [comment]
Hi @peterwilsoncc from my cursory understanding of the library and it's workings, shouldn't this be done locally? Or does it need to be updated in the project?

**Comment by peterwilsoncc** [comment]
@punndcoder28 You run the command above locally to update the `package-lock.json` file to refer the latest database. You can see an equivalent PR on Distributor https://github.com/10up/distributor/pull/1059

**Comment by punndcoder28** [comment]
Thanks for pointing out how it should be done. I ran the following commands as suggested in the issue description which results in the error mentioned [here](https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages). I also do not want to run the install command with `--legacy-peer-deps` as it might lead to other dependency related issues with the project. Here are my npm and node versions

npm: `8.19.3`
node: `19.2.0`

Should I use any other version than the ones mentioned above?

**Comment by peterwilsoncc** [comment]
It looks like the GitHub actions run using node 12 so maybe give that a try. The linked npm version appears to be around 6.14.16. If you haven't got a node version manager installed already then https://github.com/Schniz/fnm/ is great.

https://github.com/10up/publisher-media-kit/blob/7c3c6406af0e0d7ec22a8f9b910b0fed5ede354a/.github/workflows/lint.yml#L22-L25

**Comment by punndcoder28** [comment]
Ended up using `nvm` since it was already on my machine. Will be sending out a PR from my forked repo.

**Comment by punndcoder28** [comment]
I have opened up PR #150 which should fix this issue.
