### ISSUE TITLE
[How To] Build the project locally for development

### ISSUE THREAD

**Issue by punndcoder28** [10up/publisher-media-kit#152]
### Describe your question

Hi! I wanted to contribute to the project by working on a couple of issues reported. I have forked the project but I am trying to understand how to build the project locally to work on the changes and test them out but I cannot find a guide which will help me do so. Would love if anyone could point me in the right direction regarding what I have to do. Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@punndcoder28 Thank you for your question. As steps are outlined in the [CONTRIBUTING.md](https://github.com/10up/publisher-media-kit/blob/develop/CONTRIBUTING.md) file on how to build a project locally:

1. Install Composer dependencies by running `composer install`.
2. Install NPM dependencies by running `npm install`.
3. Start a development server by running `npm run watch`. This will watch your files for changes and automatically rebuild the project when you save changes.
4. Build the project for production by running `npm run build`. This will create a production-ready version of the project.

If you need any further assistance, please let me know.
