### ISSUE TITLE
Test with WP 6.3

### ISSUE THREAD

**Issue by faisal-alvi** [10up/publisher-media-kit#157]
The Publisher Media Kit and WordPress 6.3 should be tested, given this paragraph from an [article on the WP Tavern](https://wptavern.com/wordpress-6-3-beta-2-released-ready-for-testing):

> Patterns are also getting a big boost in this release, as reusable blocks have been [renamed to “synced patterns.”](https://wptavern.com/reusable-blocks-renamed-to-patterns-with-synced-and-non-synced-options) Pattern creation is now available to users and a new pattern library will be located inside the editor for saving and managing both synced and unsynced patterns. Theme authors now have the capability to register custom patterns to templates, so they appear in the start modal to speed up page building.

It'll be good to test PMK with WP 6.3 to see if the PMK patterns appear as expected in this new pattern library and are accessible within the editor as expected.

**Comment by faisal-alvi** [comment]
I have tested and found the patterns work as expected in WordPress 6.3 (RC3).

- [x] The PMK patterns appear as expected in the new pattern library
- [x] The PMK patterns are accessible within the editor as expected.

![image](https://github.com/10up/publisher-media-kit/assets/25176325/24cfa258-3ac6-427c-8af7-bfcd332214bb)

cc @jeffpaul

**Comment by jeffpaul** [comment]
@faisal-alvi still need to bump to 6.3, yeah?
https://github.com/10up/publisher-media-kit/blob/e3be14acb9d21ea7ad4265bd9e6e61cb0e0cf9ab/readme.txt#L5
