### ISSUE TITLE
Missing build creation info in 'README.md'

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/publisher-media-kit#172]
This plugin requires some commands like installing npm, composer and build commands. Would be great if add this info in 'README.md'. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@ankitguptaindia those aren't needed to use the plugin ZIP though, right?  And are those the items noted here https://github.com/10up/publisher-media-kit/blob/develop/CONTRIBUTING.md#installation?

**Comment by ankitguptaindia** [comment]
>those aren't needed to use the plugin ZIP though, right? 

Yes, those aren't needed when using plugin zip directly. 

>And are those the items noted here https://github.com/10up/publisher-media-kit/blob/develop/CONTRIBUTING.md#installation?

I missed checking 'CONTRIBUTING.md' file. That info is already here. So all looks good. Closing this issue
