### ISSUE TITLE
Frontend Issues

### ISSUE THREAD

**Issue by sudip-md** [10up/publisher-media-kit#183]
Issue 01 - Spacing issue on 'Audience Profiles' Section
Screenshot - https://prnt.sc/ciN6xwsMxyBX
-----
Issue 02 - Spacing issue on 'Why you should choose digital' Section
Screenshot - https://prnt.sc/XuwnAeRbb58W
-----
Issue 03 - Font is different in all section
Screenshot - https://prnt.sc/JrCLiZOwDW0x
-----
Issue 04 - Background color is missing in 'Our package' and 'Why you should choose digital' section
Screenshot - https://prnt.sc/Ull18Tx7a_4X
-----
Issue 05 - Background colour is missing in table block
Screenshot -  ![image](https://github.com/10up/publisher-media-kit/assets/94599521/9222aad6-b4db-4783-9509-c99d75690468)

Issue 06 - https://prnt.sc/qC-sL61HxK81
-----

### Steps to Reproduce

1. Active Plugin
2. Go to Pages
3. Edit 'Media Kit' Page
4. Open FE of Media kit page

### Environment information

**Environment**
WordPress -  6.5-RC3-57856
Google Chrome - Version 121.0.6167.184 (Official Build) (arm64) 
OS - macOS Sonoma 14.2
PHP - 8.1.23
Web Server - nginx
Database - MySQL 8.0.16
Active Plugins Version : Version 1.3.3
Themes: Twenty Twenty-Four[Version: 1.0]

### WordPress information

WordPress -  6.5-RC3-57856

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by c-v-pop** [comment]
Hi, I'm interested in helping with these issues, any pointers as just starting out contributing on open source?
