### ISSUE TITLE
Fatal Error Triggered with latest version of Simple Local Avatars

### ISSUE THREAD

**Issue by shelb-elliott** [10up/publisher-media-kit#200]
### Describe the bug

When you activate the latest versions of Publisher Media Kit & Simple Local Avatars, it triggers a fatal error.

`Fatal error: Cannot redeclare minimum_php_requirement() (previously declared in /srv/htdocs/wp-content/plugins/publisher-media-kit/publisher-media-kit.php:33) in /srv/htdocs/wp-content/plugins/simple-local-avatars/simple-local-avatars.php on line 26`

### Steps to Reproduce

1. Install & activate Simple Local Avatars
2. Install & activate Publisher Media Kit

### Screenshots, screen recording, code snippet

See description

### Environment information

-Device: MacBook Pro 14 inch, 2021 Apple M1 Pro Chip
-OS: macOS 14.5 (23F79)
-Browser: Version 126.0.6478.127 (Official Build) (arm64)

### WordPress information

`
### wp-core ###

version: 6.6.1
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress/core/6.6.1
wordpress_size: loading...
uploads_path: /srv/htdocs/wp-content/uploads
uploads_size: loading...
themes_path: /srv/htdocs/wp-content/themes
themes_size: loading...
plugins_path: /srv/htdocs/wp-content/plugins
plugins_size: loading...
fonts_path: /srv/htdocs/wp-content/uploads/fonts
fonts_size: loading...
database_size: loading...
total_size: loading...

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: Newspack (newspack-theme)
version: 1.91.0
author: Automattic
author_website: https://newspack.com
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, post-thumbnails, automatic-feed-links, title-tag, menus, html5, custom-logo, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-style, editor-font-sizes, editor-color-palette, editor-gradient-presets, custom-spacing, responsive-embeds, amp, post-subtitle, infinite-scroll, jetpack-responsive-videos, jetpack-geo-location, jetpack-content-options, woocommerce, web-stories, widgets
theme_path: /srv/htdocs/wp-content/themes/newspack-theme
auto_update: Updates managed by host

### wp-themes-inactive (6) ###

Newspack Joseph: version: 1.91.0, author: Automattic, Updates managed by host
Newspack Katharine: version: 1.91.0, author: Automattic, Updates managed by host
Newspack Nelson: version: 1.91.0, author: Automattic, Updates managed by host
Newspack Sacha: version: 1.91.0, author: Automattic, Updates managed by host
Newspack Scott: version: 1.91.0, author: Automattic, Updates managed by host
Twenty Twenty-One: version: 2.3, author: the WordPress team, Updates managed by host

### wp-mu-plugins (1) ###

Health Check Troubleshooting Mode: author: (undefined), version: 1.9.1

### wp-plugins-active (26) ###

Akismet Anti-spam: Spam Protection: version: 5.3.3, author: Automattic - Anti-spam Team, Updates managed by host
AutomateWoo: version: 6.0.29, author: WooCommerce (latest version: 6.0.30), Auto-updates enabled
Force Jetpack 2FA: version: 0.1, author: Brandon Kraft, Josh Betz, Automattic, Auto-updates enabled
Health Check & Troubleshooting: version: 1.7.1, author: The WordPress.org community, Auto-updates enabled
Jetpack: version: 13.7-a.5, author: Automattic, Updates managed by host
Jetpack 2FA for Newspack: version: 0.3.2, author: Eddie Carrasco, Automattic, Auto-updates enabled
Jetpack AI Assistant Off: version: 0.1, author: Automattic, Auto-updates enabled
Newspack: version: 4.6.1, author: Automattic, Updates managed by host
Newspack Ads: version: 2.1.0, author: Automattic, Updates managed by host
Newspack Blocks: version: 3.5.0, author: Automattic, Updates managed by host
Newspack Campaigns: version: 2.34.1, author: Automattic, Updates managed by host
Newspack Listings: version: 2.16.0, author: Automattic, Updates managed by host
Newspack Manager: version: 1.60.0, author: Automattic, Updates managed by host
Newspack Newsletters: version: 2.20.4, author: Automattic, Updates managed by host
Newspack Sponsors: version: 1.13.1, author: Automattic, Updates managed by host
Perfmatters: version: 2.3.1, author: forgemedia, Auto-updates enabled
PWA: version: 0.8.1, author: PWA Plugin Contributors, Auto-updates enabled
Simple Local Avatars: version: 2.7.11, author: 10up, Auto-updates enabled
Site Kit by Google: version: 1.131.0, author: Google (latest version: 1.132.0), Auto-updates enabled
User Switching: version: 1.8.0, author: John Blackbourn, Auto-updates enabled
WooCommerce: version: 9.1.2, author: Automattic (latest version: 9.1.4), Auto-updates enabled
WooCommerce Memberships: version: 1.25.1, author: SkyVerge (latest version: 1.26.7), Auto-updates enabled
WooCommerce Name Your Price: version: 3.5.9, author: Kathy Darling (latest version: 3.5.13), Auto-updates enabled
Woo Product Bundles: version: 7.2.1, author: Woo (latest version: 8.0.0.), Auto-updates enabled
WordPress Importer: version: 0.8.2, author: wordpressdotorg, Auto-updates enabled
Yoast SEO: version: 23.1, author: Team Yoast, Auto-updates enabled

### wp-plugins-inactive (1) ###

Publisher Media Kit: version: 1.3.4, author: 10up, Auto-updates enabled

### wp-media ###

image_editor: Photon_Subsizes_WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 2047M
upload_max_filesize: 2047M
max_effective_size: 2 GB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.10.0-31-amd64 x86_64
httpd_software: nginx
php_version: 8.1.29 64bit
php_sapi: fpm-fcgi
max_input_variables: 6144
time_limit: 1200
memory_limit: 512M
max_input_time: 1200
upload_max_filesize: 2047M
php_post_max_size: 2047M
curl_version: 8.7.1 OpenSSL/1.1.1w
suhosin: false
imagick_availability: false
pretty_permalinks: true
current: 2024-07-30T13:23:15+00:00
utc-time: Tuesday, 30-Jul-24 13:23:15 UTC
server-time: 2024-07-30T09:23:14-04:00

### wp-database ###

extension: mysqli
server_version: 10.6.18-MariaDB-log
client_version: mysqlnd 8.1.29
max_allowed_packet: 104857600
max_connections: 500

### wp-constants ###

WP_HOME: https://shelby-playground.newspackstaging.com
WP_SITEURL: https://shelby-playground.newspackstaging.com
WP_CONTENT_DIR: /srv/htdocs/wp-content
WP_PLUGIN_DIR: /srv/htdocs/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: utf8mb4_general_ci

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
fonts: not writable
mu-plugins: writable

### jetpack ###

site_id: 210567474
ssl_cert: No
time_diff: undefined
version_option: 13.7-a.5:1721848695
old_version: 13.7-a.3:1721231223
public: Public
master_user: #1 shelby
is_offline_mode: off
is_offline_mode_constant: off
current_user: #1 shelby
tokens_set: Blog User
blog_token: e$)Wn8OopETQP05ARlS4A(hJeMqi%!!5
user_token: GNYKVMSFgkflc1X%z$g2ay&R*#m8ks3X
version: 13.7-a.5
jp_plugin_dir: /wordpress/plugins/jetpack/13.7-a.5/
plan: complete
protect_header: {"trusted_header":"REMOTE_ADDR","segments":1,"reverse":false}
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"https:\/\/shelby-playground.newspackstaging.com","siteurl":"https:\/\/shelby-playground.newspackstaging.com","WP_HOME":"https:\/\/shelby-playground.newspackstaging.com","WP_SITEURL":"https:\/\/shelby-playground.newspackstaging.com"}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

### google-site-kit ###

version: 1.131.0
php_version: 8.1.29
wp_version: 6.6.1
reference_url: https://shelby-playground.newspackstaging.com
amp_mode: no
site_status: not-connected
user_status: not authenticated
verification_status: not-verified
connected_user_count: none
active_modules: site-verification, search-console, pagespeed-insights
recoverable_modules: none
required_scopes: 
	openid: ⭕
	https://www.googleapis.com/auth/userinfo.profile: ⭕
	https://www.googleapis.com/auth/userinfo.email: ⭕
	https://www.googleapis.com/auth/siteverification: ⭕
	https://www.googleapis.com/auth/webmasters: ⭕
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ⭕
	googlesitekit_view_dashboard: ⭕
	googlesitekit_manage_options: ⭕
	googlesitekit_update_plugins: ⭕
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ⭕
	googlesitekit_view_wp_dashboard_widget: ⭕
	googlesitekit_view_admin_bar_menu: ⭕
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ⭕
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ⭕
	googlesitekit_delegate_module_sharing_management::["search-console"]: ⭕
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adsPax: ⭕
	audienceSegmentation: ⭕
	consentModeSwitzerland: ⭕
	conversionInfra: ⭕
	gm3Components: ⭕
	rrmModule: ⭕
consent_mode: disabled
consent_api: not-detected
search-console_shared_roles: none
search-console_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: none

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@shelb-elliott thanks for the report. Please note that we've already fixed this issue in #197 and will be publishing a release shortly.

**Comment by faisal-alvi** [comment]
@shelb-elliott please upgrade to the latest version [1.3.5](https://wordpress.org/plugins/publisher-media-kit/), which includes the fix.
