### ISSUE TITLE
Update gender icons to be outlines only

### ISSUE THREAD

**Issue by jeffpaul** [10up/publisher-media-kit#43]
**Is your enhancement related to a problem? Please describe.**
Update male/female images to be outline only (currently can be interpreted as % of audience).

**Describe the solution you'd like**
New images for male/female audience members

**Designs**
- [ ] male icon
- [ ] female icon

**Describe alternatives you've considered**

**Additional context**

**Comment by nickolas-kola** [comment]
Please find attached a .zip of the updated Gender Icons. Please confirm if this is what you are looking for, I used the images in Git as the reference and made them outline only. I've matched the colour also.

Here is the [Figma file](https://www.figma.com/file/QjOKyxQi9z2Oseybcl2FKm/Gender-Icons?node-id=4%3A23), colours and sizing can be adjusted as you require.

[Gender Icons.zip](https://github.com/10up/publisher-media-kit/files/7760700/Gender.Icons.zip)

**Comment by ajmaurya99** [comment]
@nickolas-kola could you please, provide me access to the above Figma File.

**Comment by jeffpaul** [comment]
@ajmaurya99 are you able to access the images in the ZIP file?

**Comment by nickolas-kola** [comment]
@ajmaurya99 sorry just started the day here down-under. Give it another try, I unlocked the file.
