### ISSUE TITLE
Broken images as a result of latest update

### ISSUE THREAD

**Issue by kmwilkerson** [10up/publisher-media-kit#90]
### Describe the bug

The update for images from /assets to /dist (due to a change in patterns?) has resulted in broken images for all plugin users who updated to the latest release. It seems the only way to fix this is by re-inserting the block patterns fresh and starting over with that block. But there are too many sites utilizing this plugin to explain that process for fixing 😅 

### Steps to Reproduce

1. Update to the latest version of the plugin
2. Go to the page editor for the Media Kit
3. You'll see broken links where images should be (see screenshots)
4. Preview the page and you'll see broken links on the frontend

### Screenshots, screen recording, code snippet

<img width="225" alt="Screen Shot 2022-07-12 at 12 47 27 PM" src="https://user-images.githubusercontent.com/20666833/178567770-70d196c8-3f55-48be-a063-ace3a53f31ae.png">
<img width="163" alt="Screen Shot 2022-07-12 at 12 47 36 PM" src="https://user-images.githubusercontent.com/20666833/178567780-38ce08c8-26b3-4250-abc4-2ffb12584a3b.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Looks like that came from [here](https://github.com/10up/publisher-media-kit/pull/88#issuecomment-1165044698), which was added during the release process and thus didn't make it into the changelog. Wondering if that change should just be reverted? cc/ @jeffpaul @faisal-alvi

**Comment by jeffpaul** [comment]
Yeah that seems like it was during the release process where I was trying to ensure we only pushed from GitHub to WP.org the parts of the source/built files that were really needed for plugin functionality and not just cruft/extraneous files.  We can look to get that fixed and then tag a minor release this month to fix that (and whatever else has been updated recently).

**Comment by faisal-alvi** [comment]
IMO, we should let the users know that the image paths are changed so they have to update the paths/URLs manually, and replace "assets" with "dist". If we revert the change, we must keep the images in the assets folder even though we have (complied) images in the dist folder.

Current Active installations are 100+, so taking this decision seems feasible. If everyone agrees, how do we let users know about the change? Just updating the `readme.txt` with a changelog entry? Please share your thoughts. @dkotter @jeffpaul

**Comment by kmwilkerson** [comment]
@faisal-alvi As the person that supports this plugin on about 100 of those 100+ sites 😅, an automatic re-location of the images would certainly be preferable to avoid doing it all manually. For those other sites, given that this is a publisher-based tool geared toward small to mid sized publishers with no dev support, I highly doubt they'd go to the readme to see why their images on this page are broken.

**Comment by dkotter** [comment]
> we should let the users know that the image paths are changed so they have to update the paths/URLs manually, and replace "assets" with "dist". If we revert the change, we must keep the images in the assets folder even though we have (complied) images in the dist folder

I think because this change has already gone out without warning users, the best next step is to revert this change. While I agree it's not ideal to have the same images in both the `/assets` and `/dist` directories, it ultimately isn't causing any problems. We could look in the future to eliminate the `/assets` directory but in that case I think we should add a migration script to avoid broken images for existing users.

I've added a PR that should address fix things here
